services:
  tts-controller:
    build: 
      context: ./tts-controller
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # API端口
    volumes:
      - ./config:/config  # 配置文件
      - ./data:/data  # 数据目录
      - ./plugins:/plugins  # 插件目录
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_PATH=/config/config.yml
      - LOG_PATH=/logs
    networks:
      - tts-network
    restart: unless-stopped

networks:
  tts-network:
    name: tts-network
    driver: bridge

volumes:
  models:
    driver: local
  cache:
    driver: local
  logs:
    driver: local
