services:
  tts-controller:
    container_name: tts-controller
    build: 
      context: ./tts-controller
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # API端口
    volumes:
      - ./config:/config  # 配置文件
      - ./data:/data  # 数据目录
      - ./plugins:/plugins  # 插件目录
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "965"  # docker 组 GID
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONFIG_PATH=/config/config.yml
      - LOG_PATH=/logs
    networks:
      - tts-network
    restart: unless-stopped
    develop:
      watch:
        # 同步 Python 代码变更
        - action: sync
          path: ./tts-controller/app
          target: /app/app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        # 监控依赖变更，触发重建
        - action: rebuild
          path: ./tts-controller/requirements.txt
        # 监控 Dockerfile 变更，触发重建
        - action: rebuild
          path: ./tts-controller/Dockerfile

networks:
  tts-network:
    name: tts-network
