tts_servers:
  coqui:
    name: coqui-tts
    forward_url: http://coqui-forward:8080
    webui_url: http://coqui-tts:5002
    type: coqui
    enabled: true
    supported_languages:
      - en
      - zh
      - ja
    
  bark:
    name: bark-tts
    forward_url: http://bark-forward:8080
    type: bark
    enabled: true
    supported_languages:
      - en
      - zh

controller:
  host: "0.0.0.0"
  port: 8000
  health_check_interval: 60  # 健康检查间隔（秒）

# 转发服务器通用配置
forward_server:
  timeout: 30  # 请求超时时间（秒）
  port: 8080   # 所有转发服务统一使用此端口
  retry_count: 3  # 重试次数
