tts_servers:
  coqui:
    name: coqui-tts
    type: coqui
    image: coqui-tts
    enabled: true
    supported_languages:
      - en
      - zh
      - ja
    
  bark:
    name: bark-tts
    type: bark
    image: bark-tts
    enabled: true
    supported_languages:
      - en
      - zh

controller:
  host: "0.0.0.0"
  port: 8000
  health_check_interval: 60  # 健康检查间隔（秒）

# 转发服务器通用配置
forward_server:
  timeout: 30  # 请求超时时间（秒）
  retry_count: 3  # 重试次数
